import * as fs from "node:fs";
import { createPlan, createTask, extractCwd, isConfigured, loadHookConfig, postMemoryEvent, readHookInput, writeHookOutput } from "./common.js";

type ParsedTranscript = {
  assistantMessages: string[];
  toolCallCount: number;
};

function parseTranscript(transcriptPath: string): ParsedTranscript {
  try {
    const content = fs.readFileSync(transcriptPath, "utf8");
    const assistantMessages: string[] = [];
    let toolCallCount = 0;

    for (const rawLine of content.split("\n")) {
      const line = rawLine.trim();
      if (!line) continue;
      let entry: any;
      try {
        entry = JSON.parse(line);
      } catch {
        continue;
      }

      if (entry.type === "tool_use") {
        toolCallCount += 1;
      }

      const isAssistant =
        entry.type === "assistant" ||
        entry.role === "assistant" ||
        (Array.isArray(entry.content) && entry.role === "assistant");
      if (!isAssistant) continue;

      const contentValue = entry.content;
      if (typeof contentValue === "string" && contentValue.trim()) {
        assistantMessages.push(contentValue.trim());
      } else if (Array.isArray(contentValue)) {
        const text = contentValue
          .map((item: any) => (typeof item?.text === "string" ? item.text : typeof item === "string" ? item : ""))
          .filter(Boolean)
          .join("\n")
          .trim();
        if (text) assistantMessages.push(text);
      }
    }

    return { assistantMessages, toolCallCount };
  } catch {
    return { assistantMessages: [], toolCallCount: 0 };
  }
}

function derivePlanTitle(summary: string, agentId: string): string {
  for (const line of summary.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith("#")) {
      return trimmed.replace(/^#+\s*/, "").slice(0, 120);
    }
    if (trimmed) return trimmed.slice(0, 120);
  }
  return `Plan generated by ${agentId}`;
}

function extractPlanTasks(summary: string): string[] {
  const tasks: string[] = [];
  for (const line of summary.split("\n")) {
    const trimmed = line.trim();
    if (/^[-*]\s+/.test(trimmed) || /^\d+\.\s+/.test(trimmed)) {
      const task = trimmed.replace(/^([-*]|\d+\.)\s+/, "").trim();
      if (task) tasks.push(task);
    }
  }
  return Array.from(new Set(tasks)).slice(0, 20);
}

export async function runSubagentStopHook(): Promise<void> {
  const input = readHookInput<Record<string, unknown>>();
  const cwd = extractCwd(input);
  const config = loadHookConfig(cwd);

  if (!isConfigured(config)) {
    writeHookOutput();
    return;
  }

  const agentType =
    (typeof input.agent_type === "string" && input.agent_type) ||
    (typeof input.subagent_type === "string" && input.subagent_type) ||
    "unknown";
  const agentId = (typeof input.agent_id === "string" && input.agent_id) || "unknown";
  const transcriptPath =
    (typeof input.agent_transcript_path === "string" && input.agent_transcript_path) ||
    (typeof input.transcript_path === "string" && input.transcript_path) ||
    "";

  const transcript =
    transcriptPath && fs.existsSync(transcriptPath)
      ? parseTranscript(transcriptPath)
      : { assistantMessages: [], toolCallCount: 0 };

  const summaryText =
    transcript.assistantMessages.join("\n\n") ||
    (typeof input.summary === "string" && input.summary) ||
    "(No assistant output found in subagent transcript.)";

  if (agentType.toLowerCase() === "plan") {
    const suppliedPlanId =
      (typeof input.plan_id === "string" && input.plan_id) ||
      (typeof input.planId === "string" && input.planId) ||
      null;
    const planTitle = derivePlanTitle(summaryText, agentId);
    const planId = suppliedPlanId || (await createPlan(config, planTitle, summaryText.slice(0, 12000)));
    const tasks = extractPlanTasks(summaryText);
    let createdTaskCount = 0;
    if (planId) {
      for (const task of tasks) {
        const created = await createTask(config, {
          title: task,
          planId,
          status: "pending",
        });
        if (created) createdTaskCount += 1;
      }
    }

    await postMemoryEvent(
      config,
      "Plan subagent captured",
      {
        agent_type: "Plan",
        agent_id: agentId,
        plan_title: planTitle,
        plan_id: planId,
        supplied_plan_id: suppliedPlanId,
        extracted_task_count: tasks.length,
        created_task_count: createdTaskCount,
        assistant_message_count: transcript.assistantMessages.length,
        tool_call_count: transcript.toolCallCount,
        summary_preview: summaryText.slice(0, 2000),
        timestamp: new Date().toISOString(),
      },
      ["hook", "subagent_stop", "plan"]
    ).catch(() => {});
  } else {
    await postMemoryEvent(
      config,
      `Subagent finished: ${agentType}`,
      {
        agent_type: agentType,
        agent_id: agentId,
        summary: summaryText.slice(0, 4000),
        assistant_message_count: transcript.assistantMessages.length,
        tool_call_count: transcript.toolCallCount,
        timestamp: new Date().toISOString(),
      },
      ["hook", "subagent_stop", agentType]
    ).catch(() => {});
  }

  writeHookOutput();
}

const isDirectRun =
  process.argv[1]?.includes("subagent-stop") || process.argv[2] === "subagent-stop";
if (isDirectRun) {
  runSubagentStopHook().catch(() => process.exit(0));
}
